Server: Server.cpp
	/opt/homebrew/Cellar/gcc/12.2.0/bin/g++-12 *.cpp -o Server -I../EMP_Toolkit -I/usr/local/include -L/opt/homebrew/Cellar/zeromq/4.3.4/lib -lzmq -L/opt/homebrew/opt/openssl/lib -lcrypto -pthread -Wall -funroll-loops -Wno-ignored-attributes -Wno-unused-result -march=armv8-a+simd+crypto+crc -std=c++11 -O3

clean:
	rm -f Server