Client: Client.cpp
	/opt/homebrew/Cellar/gcc/12.2.0/bin/g++-12 *.cpp -o Client -I../EMP_Toolkit -I/usr/local/include -L/opt/homebrew/Cellar/zeromq/4.3.4/lib -lzmq -march=armv8-a+simd+crypto+crc -O3

clean:
	rm -f Client